.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. coinbit_qt test_coinbit_qt
clean: FORCE
	$(MAKE) -C .. coinbit_qt_clean test_coinbit_qt_clean
check: FORCE
	$(MAKE) -C .. test_coinbit_qt_check
coinbit-qt coinbit-qt.exe: FORCE
	 $(MAKE) -C .. coinbit_qt
